### ISSUE TITLE
 Does sx1281 work?

### ISSUE THREAD

**Issue by zhuwei** [crteensy/ELRS-8285-1280-5xPWM#4]

**Comment by crteensy** [comment]
Yes, for now.

ELRS currently doesn't use the SX1280's ranging features, and they are the only difference between '80 and' 81. In fact many receivers are currently built with the '81.

There are no plans to use ranging features in the foreseeable future (at least that's what I understood from discussions in the ELRS discord) so if you want to build this and only have the' 81, go for it.

**Comment by zhuwei** [comment]
Thank you very much. I'm going to try
