### ISSUE TITLE
Can you provide Gerber file?

### ISSUE THREAD

**Issue by zhuwei** [crteensy/ELRS-8285-1280-5xPWM#5]

**Comment by zhuwei** [comment]
If only you could provide a physical picture

**Comment by crteensy** [comment]
Sure I can provide gerbers - which PCB manufacturer would you use? They have slightly different preferences for the settings

The ESP8285 antenna is the straight PCB trace antenna along the left edge in this screenshot:
![image](https://user-images.githubusercontent.com/7403405/171503951-d69cf9bc-31ea-4add-a4e3-e530249a3f3f.png)

**Comment by crteensy** [comment]
Little heads up: I just updated the repo

**Comment by zhuwei** [comment]
I willI intend to use eda/jlc supplier(www.jlc.com).
thks!

**Comment by zhuwei** [comment]
![QQ截图20220602093627](https://user-images.githubusercontent.com/1817493/171528759-be167eda-e5f7-40a7-be7a-7479c19889f2.png)
what's this?

**Comment by crteensy** [comment]
That's the RF filter: Johanson 2450FM07D0034T

**Comment by crteensy** [comment]
See if these are ok for you (PCB rev 0.6)

[ELRS_ESP8285_PWM5_rev0.6-jlcpcb.zip](https://github.com/crteensy/ELRS-8285-1280-5xPWM/files/8827708/ELRS_ESP8285_PWM5_rev0.6-jlcpcb.zip)

**Comment by zhuwei** [comment]
Thank you very much!
